---
abstract: ' Perl interface to flic.kr'
author:
  - 'Shinsuke Matsui <smatsui@karashi.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-Flickr
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Encode::Base58: 0
  WWW::Shorten: 0
resources:
  homepage: http://github.com/poppen/p5-WWW-Shorten-Flickr/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/poppen/p5-WWW-Shorten-Flickr.git
version: 0.02
